export enum CLICommand {
  AddDependencies = 'adddependencies',
  CreateProject = 'createproject',
  Deploy = 'deploy',
  ImportBundle = 'importbundle',
  ImportFiles = 'importfiles',
  ImportObjects = 'importobjects',
  ListBundles = 'listbundles',
  ListConfiguration = 'listconfiguration',
  ListFiles = 'listfiles',
  ListMissingDependencies = 'listmissingdependencies',
  ListObjects = 'listobjects',
  Preview = 'preview',
  Update = 'update',
  UpdateCustomRecordsWithInstances = 'updatecustomrecordwithinstances',
  // UploadFolders = 'uploadfolders',
  Validate = 'validate',
}
